redis-master:
  image: redis:6.0.4
  container_name: redis-master

redis-slave1:
  image: redis:6.0.4
  command: redis-server --replicaof redis-master 6379 --bind 0.0.0.0
  container_name: redis-slave1
  links:
  - redis-master

redis-slave2:
  image: redis:6.0.4
  command: redis-server --replicaof redis-master 6379 --bind 0.0.0.0
  container_name: redis-slave2
  links:
  - redis-master

redis-slave3:
  image: redis:6.0.4
  command: redis-server --replicaof redis-master 6379 --bind 0.0.0.0
  container_name: redis-slave3
  links:
  - redis-master

sentinel:
  build: sentinel
  environment:
  - SENTINEL_DOWN_AFTER=5000
  - SENTINEL_FAILOVER=5000
  - SENTINEL_QUORUM=1
  links:
  - redis-master
  - redis-slave1
  - redis-slave2   
  - redis-slave3 

haproxy:
  image: myhaproxy:1.0
  links:
  - redis-master
  - redis-slave1
  - redis-slave2   
  - redis-slave3    